#!/bin/sh -e


if [ -x /usr/bin/cert-sync ]; then
        echo "Updating Mono key store..."
# always return true, even if the tool blows up for some reason.
# we don't want to mess with users at install-time. failure here
# isn't really fatal anyway, just inconvenient
        /usr/bin/cert-sync /etc/ssl/certs/ca-certificates.crt || true
        echo "Done"
fi
